<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config[
<!ELEMENT lockss-config (if|property)+>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
]>

<lockss-config>
    <property name="org.lockss">
        <if>
            <or>
                <test group="abc" />
                <test group="def" />
                <test group="prod" />
                <test group="hij" />
            </or>
            <then>
                <property name="id.initialV3PeerList">
                    <list>
                        <value>TCP:[1.2.3.4]:9729</value>
                        <value>TCP:[5.6.7.8]:9729</value>
                    </list>
                </property>
            </then>
        </if>
        <if>
            <or>
                <test hostname="test1.example.org"/>
                <test hostname="test2.example.org"/>
                <test hostname="test3.example.org"/>
                <test hostname="test4.example.org"/>
            </or>
            <then>
                <property name="id.initialV3PeerList">
                    <list>
                        <value>TCP:[4.3.2.1]:9729</value>
                        <value>TCP:[8.7.6.5]:9729</value>
                    </list>
                </property>
            </then>
        </if>
    </property>
</lockss-config>
